### ISSUE TITLE
Feature request - Mise en place du mirroring GitLab

### ISSUE THREAD

**Issue by LeGrizzly** [xalsie/tp1_git#19]
## Description
Nous souhaitons ajouter la fonctionnalité de mirroring (réplication) de notre dépôt Git vers GitLab. Actuellement, notre projet est hébergé sur un dépôt Git local, mais nous souhaitons également disposer d'une copie du code source sur GitLab, afin de bénéficier de ses fonctionnalités supplémentaires et de faciliter la collaboration avec d'autres développeurs.

## Objectif
L'objectif de cette issue est de mettre en place le mirroring de notre dépôt Git vers GitLab, en veillant à ce que toutes les branches, les tags et les modifications soient synchronisées en temps réel entre les deux plates-formes.

## Tâches à effectuer
1. Créer un nouveau projet sur GitLab pour accueillir la copie miroir de notre dépôt Git.
2. Configurer le mirroring en utilisant les fonctionnalités intégrées de GitLab ou en utilisant des outils externes tels que GitLab CI/CD ou des scripts Git.
3. S'assurer que toutes les branches, les tags et les modifications du dépôt Git sont correctement répliqués vers GitLab.
4. Planifier la fréquence de mise à jour du mirroring pour maintenir les deux dépôts à jour en temps réel ou selon un calendrier défini.
5. Effectuer des tests pour vérifier que les modifications effectuées sur GitLab sont correctement synchronisées avec le dépôt Git, et vice versa.

## Critères d'acceptation
- Le mirroring est configuré et fonctionne correctement, assurant la réplication en temps réel des branches, des tags et des modifications entre le dépôt Git et GitLab.
- Toutes les branches, les tags et les modifications sont correctement synchronisés entre les deux plates-formes, sans perte de données.
- Les développeurs peuvent facilement collaborer et travailler sur le projet à partir de GitLab, en utilisant ses fonctionnalités supplémentaires telles que les demandes de fusion (merge requests), les problèmes (issues), etc.

N'hésitez pas à poser des questions si vous avez besoin de plus d'informations sur cette issue.

**Comment by LeGrizzlyDev** [comment]
Pas nécessaire pour le moment.
